import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image"

const Home: NextPage = () => {
  // TODO: Migrate to Document component to support this JS https://nextjs.org/docs/advanced-features/custom-document
  // let tabs = document.querySelectorAll(".tab");
  // let panels = document.querySelectorAll(".panel");
  // let projectNav = document.querySelector(".projectTabNav");

  // projectNav.addEventListener("click", (event) => {
  //   const id = event.target.dataset.id;
  //   if (id) {
  //     tabs.forEach((tab) => {
  //       //change active on tabs
  //       tab.classList.remove("active");
  //       event.target.classList.add("active");
  //     });
  //     //change active on panels
  //     panels.forEach((panel) => {
  //       panel.classList.remove("active");
  //     });
  //     const activePanel = document.getElementById(id);
  //     activePanel.classList.add("active");
  //   }
  // });

  return (
    <div>
      <Head>
        <title>Amber Jones | Development Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <section id='headline'>
          <h1>Amber Jones</h1>
          <h2>Web Developer</h2>
        </section>

        <section className='flex' id='intro'>
          <div id='about'>
            <div className='frame' id='about-box'>
              <p>Hello, World!</p>

              <p>
                I&#x27;m Amber, and I am a former Cosmetologist working toward
                becoming a Web Developer. In June of 2020, when most of the
                world shut down, I began learning to code, a goal I have had for
                some time.
              </p>

              <p>
                I started by taking front-end development classes with SheCodes,
                completing every class they offered at the time, then moved on
                to freeCodeCamp and Codecademy to expand on the skills I had
                acquired from my initial courses.
              </p>

              <p>
                I hope to begin work in a Junior Developer position to continue
                learning as much as possible about web development in a
                professional team environment. I am also interested in mobile
                app and software development and hope to learn languages that
                will help me in those areas once I have a good grasp on all that
                I need for front-end work.
              </p>

              <p>
                I have earned an Associates&#x27; degree in fine art, where I
                learned the basics of color theory, design, and digital art. I
                learned and worked with Adobe Photoshop, InDesign, and
                Illustrator in my classes, primarily on Mac OS, and would be
                happy to refresh these skills if necessary. I have also worked
                many years in Cosmetology, where communication, problem-solving,
                and patience have been crucial skills for success on the job.
              </p>
            </div>
          </div>

          <div id='intro-img'>
            <div className='frame' id='img-frame'>
              <Image src='/images/introimg.jpg' width={250} height={338}
                alt='portrait image of page owner'
              />
            </div>
          </div>
        </section>

        <hr />

        <section id='my-work'>
          <h2>My Work</h2>
          <article className='projectTabNav'>
            <div className='btnContainer'>
              <button className='tab active' data-id='projects-panel'>
                Project Images
              </button>
              <button className='tab' data-id='links-panel'>
                Source Code
              </button>
            </div>
          </article>

          <article>
            <div className='panel active' id='projects-panel'>
              <div className='flex' id='projects-box'>
                <div className='projectCard frame' id='weather'></div>

                <div className='projectCard frame' id='tea-cozy'></div>

                <div className='projectCard frame' id='company-page'></div>

                <div className='projectCard frame' id='club-page'></div>

                <div className='projectCard frame' id='portfolio'></div>
              </div>
            </div>

            <div className='panel' id='links-panel'>
              <div className='flex' id='links-box'>
                <div className='projectCard frame links' id='weather-links'>
                  <h3 className='projectLabel' id='weather-label'>
                    Weather Web App
                  </h3>
                  <p className='skillsUsed' id='weather-skills'>
                    Two versions of a weather web application, one using pure
                    JavaScript and another using React.
                  </p>
                  <div className='flex btnBoxContainer'>
                    <div className='btnBox'>
                      <a
                        className='button weatherBtn'
                        href='https://unruffled-sammet-45d5b4.netlify.app/'
                        target='_blank' rel="noreferrer">
                        JS Live
                      </a>
                      <a
                        className='button weatherBtn'
                        href='https://github.com/ambahjones/my-weather-app'
                        target='_blank' rel="noreferrer">
                        JS Code
                      </a>
                    </div>
                    <div className='btnBox'>
                      <a
                        className='button weatherBtn'
                        href='https://focused-brattain-c3d371.netlify.app/'
                        target='_blank' rel="noreferrer">
                        React Live
                      </a>
                      <a
                        className='button weatherBtn'
                        href='https://github.com/ambahjones/weather-react'
                        target='_blank' rel="noreferrer">
                        React Code
                      </a>
                    </div>
                  </div>
                </div>

                <div className='projectCard frame links' id='tea-cozy-links'>
                  <h3 className='projectLabel' id='tea-label'>
                    Tea Cozy mock website
                  </h3>
                  <p className='skillsUsed' id='tea-skills'>
                    Flex box practice project usng course provided images and
                    design spec sheet.
                  </p>
                  <div className='btnBox2'>
                    <a
                      className='button'
                      href='https://ambahjones.github.io/tea-cozy/'
                      target='_blank' rel="noreferrer">
                      Live
                    </a>
                    <a
                      className='button'
                      href='https://github.com/ambahjones/tea-cozy'
                      target='_blank' rel="noreferrer">
                      Code
                    </a>
                  </div>
                </div>

                <div
                  className='projectCard frame links'
                  id='company-page-links'>
                  <h3 className='projectLabel' id='company-label'>
                    Faux Company Homepage
                  </h3>
                  <p className='skillsUsed' id='company-skills'>
                    Homepage for a self created company using flex box and an
                    individual design.
                  </p>
                  <div className='btnBox2'>
                    <a
                      className='button'
                      href='https://ambahjones.github.io/company-homepage/'
                      target='_blank' rel="noreferrer">
                      Live
                    </a>
                    <a
                      className='button'
                      href='https://github.com/ambahjones/company-homepage'
                      target='_blank' rel="noreferrer">
                      Code
                    </a>
                  </div>
                </div>

                <div className='projectCard frame links' id='club-page-links'>
                  <h3 className='projectLabel' id='club-label'>
                    Faux club events page
                  </h3>
                  <p className='skillsUsed' id='club-skills'>
                    Club events page using responsive design elements. Personal
                    choice to link to company homepage.
                  </p>
                  <div className='btnBox2'>
                    <a
                      className='button'
                      href='https://ambahjones.github.io/club-page/'
                      target='_blank' rel="noreferrer">
                      Live
                    </a>
                    <a
                      className='button'
                      href='https://github.com/ambahjones/club-page'
                      target='_blank' rel="noreferrer">
                      Code
                    </a>
                  </div>
                </div>

                <div className='projectCard frame links' id='portfolio-links'>
                  <h3 className='projectLabel' id='portfolio-label'>
                    Personal page
                  </h3>
                  <p className='skillsUsed' id='portfolio-skills'>
                    The page you are currently viewing!
                  </p>
                  <div className='btnBox2' id='portfolio-btn-box'>
                    <a
                      className='button'
                      href='https://github.com/ambahjones/portfolio'
                      target='_blank' rel="noreferrer">
                      Code
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </article>
        </section>

        <hr />

        <section id='skills'>
          <h2>Skills</h2>

          <div className='flex' id='skills-box'>
            <div className='skillsContainer'>
              <div className='skillsCard frame'>
                <Image src='/icons/html-icon.webp' alt='html icon' width={80} height={80} />
              </div>
              <p className='label'>HTML</p>
            </div>

            <div className='skillsContainer'>
              <div className='skillsCard frame'>
                <Image src='/icons/css-icon.webp' alt='css icon' width={80} height={80} />
              </div>
              <p className='label'>CSS</p>
            </div>

            <div className='skillsContainer'>
              <div className='skillsCard frame'>
                <Image src='/icons/javascript-icon.webp' alt='javascript icon' width={80} height={80} />
              </div>
              <p className='label'>JavaScript</p>
            </div>

            <div className='skillsContainer'>
              <div className='skillsCard frame'>
                <Image src='/icons/react-icon.webp' alt='react icon' width={80} height={80} />
              </div>
              <p className='label'>React</p>
            </div>
          </div>
        </section>

        <hr />

        <section id='contact'>
          <h2>Contact Me</h2>
          <div className='flex' id='contact-box'>
            <div className='contactCard frame'>
              <a href='mailto:amber.jonesn@gmail.com'>
                <Image src='/icons/mail icon.webp' alt='email icon' width={80} height={80} />
              </a>
            </div>

            <div className='contactCard frame'>
              <a href='https://github.com/ambahjones' target='_blank' rel="noreferrer">
                <Image src='/icons/github-icon.webp' alt='github icon' width={80} height={80} />
              </a>
            </div>

            <div className='contactCard frame'>
              <a
                href='https://www.linkedin.com/in/amber-jones-0712272b/'
                target='_blank' rel="noreferrer">
                <Image src='/icons/linkedin icon.webp' alt='linkedin icon' width={80} height={80} />
              </a>
            </div>

            <div className='contactCard frame'>
              <a href='https://twitter.com/ambahjones' target='_blank' rel="noreferrer">
                <Image src='/icons/twitter icon.webp' alt='twitter icon' width={80} height={80} />
              </a>
            </div>
          </div>
        </section>
      </main>

      <footer className='flex'>
        <p>Developed by Amber Jones</p>
        <p>
          Images and icons from
          <a href='https://unsplash.com/' target='_blank' rel="noreferrer">
            Unsplash
          </a>{" "}
          and
          <a href='https://www.iconfinder.com/' target='_blank' rel="noreferrer">
            Iconfinder
          </a>
        </p>
      </footer>
    </div>
  );
};

export default Home;
