import styles from "../styles/resume.module.css";
import type { NextPage } from "next";
import Head from "next/head";

const Resume: NextPage = () => {
  // TODO: Migrate remaining classes to CSS modules.

  return (
    <div>
      <Head>
        <title>Amber Jones | Resume</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <section id='header-box'>
          <h1>Amber Jones</h1>
          <ul>
            <li id='city'>Philadelphia, PA</li>
            <li>
              <a href='mailto:amber.jonesn@gmail.com'>amber.jonesn@gmail.com</a>
            </li>
          </ul>
        </section>
        <hr />
        <section id='summary'>
          <h2 className='resHeader'>Entry Level Developer</h2>
          <p className={styles.resArticle}>
            Self taught and motivated junior web developer looking for a
            position to learn and grow in. Willing to and interested in learning
            languages other than those listed below. Work examples can be viewed
            on
            <a className={styles.resLink} href='https://github.com/ambahjones'>
              Github
            </a>{" "}
            and additional information on
            <a
              className={styles.resLink}
              href='https://www.linkedin.com/in/amber-jones-0712272b/'>
              LinkedIn
            </a>
            .
          </p>
        </section>
        <hr />
        <section id='education'>
          <h2 className='resHeader'>Education</h2>
          <div className={styles.resArticle}>
            <p className={`${styles.edInfo} ${styles.edSource}`}>
              <em>SheCodes: Online</em>
            </p>
            <p className='edInfo dates'>
              <em>June 2020 - September 2020</em>
            </p>
            <ul className={styles.edList}>
              <li>
                Completed introductory and intermediate front end development
                workshops
              </li>
              <li>Completed React workshop</li>
            </ul>
          </div>
          <div className={styles.resArticle}>
            <p className={`${styles.edInfo} ${styles.edSource}`}>
              <em>Codecademy Pro: Online</em>
            </p>
            <p className='edInfo dates'>
              <em>September 2020 - present</em>
            </p>
            <ul className={styles.edList}>
              <li>Expanding upon knowledge gained from SheCodes</li>
              <li>
                Completed interactive website and intermediate
                <abbr title='Cascading Style Sheets'>CSS</abbr> classes
              </li>
              <li>
                Working to complete full stack development path to better
                understand all aspects of web development
              </li>
            </ul>
          </div>
        </section>
        <hr />
        <section id='tech'>
          <h2 className='resHeader'>Technology Experience</h2>
          <div className={styles.resArticle}>
            <p>
              <em>Basics:</em>
              <abbr title='Hyper Text Markup Language'>HTML</abbr>,
              <abbr title='Cascading Style Sheets'>CSS</abbr> (media queries,
              flexbox, and accessibility)
            </p>
            <p>
              <em>Languages:</em> JavaScript, React
            </p>
            <p>
              <em>Additional workflow tools:</em> Git, Github (including Github
              desktop for Mac), Slack
            </p>
            <p>
              <em>Systems:</em> Mac OS (current version: Big Sur)
            </p>
          </div>
        </section>
      </main>

      <footer className='flex'>
        <p>Developed by Amber Jones</p>
        <p>
          Images and icons from
          <a href='https://unsplash.com/' target='_blank' rel='noreferrer'>
            Unsplash
          </a>{" "}
          and
          <a href='https://www.iconfinder.com/' target='_blank' rel='noreferrer'>
            Iconfinder
          </a>
        </p>
      </footer>
    </div>
  );
};

export default Resume;
